version: "3.0"

services:
  grafana:
    image: grafana/grafana:7.0.6
    volumes:
      - grafanadata:/var/lib/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - influxdb
      - elasticsearch

  fluentd:
    build: .
    volumes:
      - .:/fluentd/etc
      - fluentdata:/data
    env_file:
      - .env
    depends_on:
      - influxdb
      - elasticsearch

  influxdb:
    image: influxdb:1.8.0
    volumes:
      - influxdata:/var/lib/influxdb
    env_file:
      - .env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

volumes:
  grafanadata:
  fluentdata:
  elasticdata:
  influxdata:
