version: "3.0"

services:
  influxdb:
    image: influxdb:1.8.0
    env_file:
      - .env
    volumes:
      - influxdata:/var/lib/influxdb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

volumes:
  elasticdata:
  influxdata:
